---
- name: Forbirdden Fedora
  hosts: localhost
  become: yes

  tasks:

    - name: Disable SELinux
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'

    - name: Get AppImageLauncher RPM URL
      set_fact:
        appimglaunch: "{{ (lookup('url', 'https://api.github.com/repos/TheAssassin/AppImageLauncher/releases/tags/continuous', split_lines=False) | from_json).assets | selectattr('name', 'search', 'x86_64\\.rpm$') | map(attribute='browser_download_url') | first }}"

    - name: Install RPM Fusion
      dnf:
        name:
          - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
          - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: latest
        disable_gpg_check: yes

    - name: Install drivers
      dnf:
        name:
          - linux-firmware
          - kernel-modules-extra
          - mesa-vulkan-drivers
          - mesa-vulkan-drivers.i686
          - mesa-va-drivers-freeworld
          - mesa-va-drivers-freeworld.i686
          - mesa-vdpau-drivers-freeworld
        state: latest

    - name: Install RPMs
      dnf:
        name:
          - fastfetch
          - flatpak
          - gnome-shell
          - gdm
          - nautilus
          - gnome-terminal
          - gnome-control-center
          - gnome-software
          - gnome-tweaks
          - nemo
          - nemo-extensions
          - "{{ appimglaunch }}"
          - steam
          - gamemode
          - gamemode.i686
          - pipx
          - openssl
          - curl
          - wget
          - unzip
          - dbus-x11
          - plymouth
          - plymouth-theme-spinner
        state: latest
        disable_gpg_check: true

    - name: Add Flatpak repo
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system

    - name: Install Flatpaks
      community.general.flatpak:
        method: system
        name: 
          - com.discordapp.Discord
          - org.mozilla.firefox
          - org.vinegarhq.Sober
          - com.usebottles.bottles
          - org.telegram.desktop
          - org.videolan.VLC
          - com.github.tchx84.Flatseal
          - com.obsproject.Studio
          - com.visualstudio.code
          - com.mattjakeman.ExtensionManager
          - org.qbittorrent.qBittorrent
          - org.libreoffice.LibreOffice
          - com.protonvpn.www
          - io.github.flattool.Warehouse
          - org.torproject.torbrowser-launcher
          - io.missioncenter.MissionCenter
          - com.anydesk.Anydesk
          - im.riot.Riot
          - io.github.thetumultuousunicornofdarkness.cpu-x
          - dev.lizardbyte.app.Sunshine
          - org.virt_manager.virt-manager
          - io.github.shiftey.Desktop
          - org.kde.kate
          - org.raspberrypi.rpi-imager
        state: latest

    - name: Install WHLs
      become: no
      shell: |
        pipx install gnome-extensions-cli yt-dlp --force
        pipx ensurepath

    - name: Install GNOME extensions
      become: no
      shell: |
        dbus-run-session ~/.local/bin/gnome-extensions-cli install {{ item }}
      loop:
        - dash-to-panel@jderose9.github.com
        - appindicatorsupport@rgcjonas.gmail.com
        - arcmenu@arcmenu.com
        - gsconnect@andyholmes.github.io
        - ding@rastersoft.com
        - blur-my-shell@aunetx
        - user-theme@gnome-shell-extensions.gcampax.github.com

    - name: Recursively copy rootfs directory into root
      ansible.builtin.copy:
        src: "./rootfs/"
        dest: "/"

    - name: Load dconf config
      become: no
      shell: |
        dbus-run-session dconf load / < /tmp/settings.dconf

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Make autoupdate.sh executable
      file:
        path: /usr/local/bin/autoupdate.sh
        mode: '0755'

    - name: Enable packages autoupdate at startup and every 3 hours 
      systemd:
        name: autoupdate.timer
        enabled: yes
        state: started

    - name: Enable Plymouth and disable SELinux in GRUB
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX="(.*)"'
        line: 'GRUB_CMDLINE_LINUX="\1 rhgb quiet selinux=0"'
        backrefs: yes

    - name: Update GRUB configuration
      shell: grub2-mkconfig -o /boot/grub2/grub.cfg

    - name: Enable GDM
      systemd:
        name: gdm
        enabled: yes

    - name: Set graphical.target as default
      systemd:
        name: graphical.target
        enabled: yes
        masked: no

    - name: Enable fstrim.timer
      systemd:
        name: fstrim.timer
        enabled: yes
        state: started

    - name: Download Vencord Installer 
    get_url:
      url: https://vencord.dev/install.sh
      dest: /home/emil/Документы/vencord.sh 
      mode: '0755'

    - name: Download Prism Launcher
    get_url:
      url: https://github.com/Diegiwg/PrismLauncher-Cracked/releases/latest/download/PrismLauncher-Linux-x86_64.AppImage
      dest: /home/emil/Загрузки/PrismLauncher-Linux-x86_64.AppImage 
      mode: '0755'

    - name: Reboot 
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      ignore_errors: true

